name: ✨ Feature Request
description: Solicitud de nueva funcionalidad
title: "[FEATURE] "
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por sugerir una nueva funcionalidad. Por favor, proporciona todos los detalles posibles.

  - type: textarea
    id: problem
    attributes:
      label: Problema a Resolver
      description: Describe el problema o necesidad que esta funcionalidad resolvería
      placeholder: "Como usuario, necesito..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solución Propuesta
      description: Describe tu solución ideal para este problema
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: ¿Has considerado otras soluciones? ¿Por qué esta es mejor?

  - type: dropdown
    id: area
    attributes:
      label: Área de Implementación
      description: ¿En qué área del sistema se implementaría?
      options:
        - Frontend (Angular/UI)
        - Backend (Spring/API)
        - Base de Datos
        - Infraestructura
        - DevOps/CI-CD
        - Múltiples áreas
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad Sugerida
      description: ¿Qué tan importante consideras esta funcionalidad?
      options:
        - P0 - Crítico (Bloquea operaciones importantes)
        - P1 - Alto (Muy importante para los usuarios)
        - P2 - Medio (Sería muy útil tenerlo)
        - P3 - Bajo (Nice to have)

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de Aceptación
      description: ¿Cómo sabremos que esta funcionalidad está completa?
      placeholder: |
        - [ ] El usuario puede...
        - [ ] El sistema debe...
        - [ ] Se muestra...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Diseños
      description: Si es aplicable, adjunta mockups o diseños de la funcionalidad

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Cualquier otra información relevante
