name: "🛡️ Security Advisory"
description: "Reportar vulnerabilidad de seguridad (PRIVADO)"
title: "[SECURITY] "
labels: ["type:security", "prio:P0"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Reporte Confidencial de Seguridad

        **Este reporte será privado y solo visible para mantenedores.**

        Por favor, NO divulgues públicamente esta vulnerabilidad hasta que sea parcheada.

  - type: input
    id: title
    attributes:
      label: "Título de la Vulnerabilidad"
      description: "Descripción concisa del problema"
      placeholder: "Ej: XSS en formulario de contacto"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Nivel de Severidad"
      options:
        - "🔴 P0 - Crítico (RCE, bypass auth completo)"
        - "🟠 P1 - Alto (Escalación privilegios, datos sensibles)"
        - "🟡 P2 - Medio (Requiere autenticación, impacto limitado)"
        - "🟢 P3 - Bajo (Impacto mínimo, teórico)"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: "Área Afectada"
      options:
        - "area:frontend"
        - "area:backend"
        - "area:db"
        - "area:infrastructure"
        - "area:devops"
        - "area:dependencies"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descripción Detallada"
      description: "Explica la vulnerabilidad técnicamente"
      placeholder: |
        La vulnerabilidad permite...
        Se encuentra en...
        El impacto es...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Pasos para Reproducir"
      description: "Instrucciones paso a paso para replicar el issue"
      placeholder: |
        1. Ir a...
        2. Hacer click en...
        3. Introducir...
        4. Observar...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Impacto Potencial"
      description: "Qué podría hacer un atacante explotando esto"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Entorno Afectado"
      description: "Versiones, navegadores, SO, etc."
      placeholder: |
        - Versión: 1.2.3
        - Navegador: Chrome 120
        - SO: Windows 11
        - Ambiente: Producción

  - type: textarea
    id: solution
    attributes:
      label: "Solución Sugerida (Opcional)"
      description: "Si tienes ideas para solucionarlo"

  - type: checkboxes
    id: terms
    attributes:
      label: "Términos y Condiciones"
      options:
        - label: "Acepto no divulgar públicamente esta vulnerabilidad hasta que sea parcheada"
          required: true
        - label: "Estoy de acuerdo con ser reconocido/a en las notas de la versión (opcional)"
          required: false
