name:  Task
description: Tarea t茅cnica espec铆fica
title: "[TASK] "
labels: ["Task", "type:chore"]
body:
  - type: markdown
    attributes:
      value: |
        Una tarea t茅cnica que no necesariamente aporta valor directo al usuario, pero es necesaria para el proyecto.

  - type: input
    id: title
    attributes:
      label: T铆tulo de la Tarea
      description: Un t铆tulo descriptivo y conciso
      placeholder: "Configurar pipeline de CI/CD para el microservicio de autenticaci贸n"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: Describe en detalle qu茅 se necesita hacer
    validations:
      required: true

  - type: dropdown
    id: task-type
    attributes:
      label: Tipo de Tarea
      options:
        - Configuraci贸n
        - Investigaci贸n
        - Actualizaci贸n de Dependencias
        - Migraci贸n
        - Optimizaci贸n
        - Documentaci贸n
        - Testing
        - Deployment
        - Monitoreo
        - Otro
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: rea
      description: 驴En qu茅 谩rea del sistema se realizar谩 la tarea?
      options:
        - Frontend (Angular/UI)
        - Backend (Spring/API)
        - Base de Datos
        - Infraestructura
        - DevOps/CI-CD
        - Documentaci贸n
        - Testing
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de Completitud
      description: 驴Qu茅 debe cumplirse para considerar esta tarea como completa?
      placeholder: |
        - [ ] Pipeline configurado y funcionando
        - [ ] Tests automatizados ejecut谩ndose
        - [ ] Documentaci贸n actualizada
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Detalles T茅cnicos
      description: Informaci贸n t茅cnica relevante, comandos, configuraciones, etc.

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencias
      description: 驴Esta tarea depende de otras tareas o sistemas?

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options:
        - P0 - Cr铆tico (Bloquea otras tareas)
        - P1 - Alto (Necesario pronto)
        - P2 - Medio (Importante pero no urgente)
        - P3 - Bajo (Cuando haya tiempo)

  - type: input
    id: estimated-hours
    attributes:
      label: Estimaci贸n (horas)
      description: Tiempo estimado para completar la tarea
      placeholder: "4"

  - type: input
    id: related-issue
    attributes:
      label: Issue Relacionado
      description: Si esta tarea est谩 relacionada con otro issue
      placeholder: "#456"
