name:  Tech Debt
description: Refactorizaci贸n o mejora t茅cnica
title: "[TECH DEBT] "
labels: ["Tech Debt", "type:refactor"]
body:
  - type: markdown
    attributes:
      value: |
        Documenta deuda t茅cnica que necesita ser abordada para mejorar la calidad del c贸digo o la arquitectura.

  - type: input
    id: title
    attributes:
      label: T铆tulo
      description: Un t铆tulo descriptivo de la deuda t茅cnica
      placeholder: "Refactorizar el m贸dulo de autenticaci贸n para usar JWT"
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Estado Actual
      description: Describe el problema actual y por qu茅 es deuda t茅cnica
      placeholder: |
        - El c贸digo actual usa sesiones en memoria
        - No es escalable horizontalmente
        - Dificulta la implementaci贸n de microservicios
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Soluci贸n Propuesta
      description: Describe c贸mo se deber铆a refactorizar o mejorar
    validations:
      required: true

  - type: dropdown
    id: debt-type
    attributes:
      label: Tipo de Deuda T茅cnica
      options:
        - C贸digo duplicado
        - Arquitectura obsoleta
        - Dependencias desactualizadas
        - Falta de tests
        - Performance
        - Seguridad
        - Documentaci贸n faltante
        - C贸digo legacy
        - Acoplamiento alto
        - Otro
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: rea Afectada
      options:
        - area:frontend
        - area:backend
        - area:db
        - area:infrastructure
        - area:devops
        - area:dependencies
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impacto de NO Resolver
      description: 驴Qu茅 problemas causar谩 si no se aborda esta deuda t茅cnica?
      placeholder: |
        - Incremento en tiempo de desarrollo de nuevas features
        - Mayor probabilidad de bugs
        - Dificultad para escalar
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Beneficios de Resolver
      description: 驴Qu茅 mejoras se obtendr谩n al resolver esta deuda?
      placeholder: |
        - Reducci贸n del 50% en tiempo de despliegue
        - Mejor mantenibilidad del c贸digo
        - Posibilidad de escalar horizontalmente

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      description: Basada en el impacto y urgencia
      options:
        - prio:P0
        - prio:P1
        - prio:P2
        - prio:P3
    validations:
      required: true

  - type: input
    id: effort
    attributes:
      label: Esfuerzo Estimado
      description: Estimaci贸n en d铆as-persona
      placeholder: "5 d铆as"

  - type: textarea
    id: migration-plan
    attributes:
      label: Plan de Migraci贸n
      description: Si aplica, describe c贸mo se migrar谩 del estado actual al deseado

  - type: textarea
    id: risks
    attributes:
      label: Riesgos
      description: Riesgos asociados con la refactorizaci贸n
